---
  - roles: 
      - ansible-role-nginx
    vars:
      nginx_http_template_enable: true
      nginx_http_template:
        default:
          port: 80
          server_name: localhost
          error_page: /usr/share/nginx/html
          autoindex: false
          web_server:
            locations:
              default:
                location: /
                html_file_location: /usr/share/nginx/html
                html_file_name: index.html
