---
  - name: Install NvIPAM
    hosts: localhost
    vars_files:
      -  vars/main.yml
      -  vars/postgresql.yml
    roles:
        - common
        - role: geerlingguy.postgresql
        - role: nginxinc.nginx
