---
  - name: Copy sql file to temp
    copy: src=files/psql-schema.sql dest=/tmp/psql-schema.sql 


  - name: Import PDNS 4.1 postgres schema
    command: psql -U nvipam -d nvipam < /tmp/psql-schema.sql
