---
  - name: Copy recursor.conf to fix issue with imported role
    copy: src=files/recursor.conf dest=/etc/pdns-recursor/recursor.conf 


  - name: Import PDNS 4.1 postgres schema
    shell: systemctl restart pdns-recursor.service 
