- name: Install base packages
  yum: name={{ item }} state=installed
  with_items:
    - locales
    - build-essential
    - ntp
    - git
    - supervisor
    - python-pip
    - python3-pip
    - nginx
  tags:
    - packages
- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
